import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type {
  AgentInputDto,
  AppSettingsDto,
  ApproveOptionsDto,
  ChatRequestDto,
  MetaPatch,
  OnboardPayload,
  RoutineStepDto,
  EngramApi,
  EngramEvent,
} from '../shared/types.js'

const api: EngramApi = {
  capturePrivate: (text: string) => ipcRenderer.invoke('capture:private', text),
  captureFile: (path: string) => ipcRenderer.invoke('capture:file', path),
  captureImage: (data: Uint8Array, locked: boolean) => ipcRenderer.invoke('capture:image', data, locked),
  hideQuickCapture: () => ipcRenderer.send('quick:hide'),
  pathForFile: (file: File) => webUtils.getPathForFile(file),
  chatSend: (request: ChatRequestDto) => ipcRenderer.invoke('chat:send', request),
  // fire-and-forget: drag deltas at pointer-move rate must never await
  activityToday: () => ipcRenderer.invoke('activity:today'),
  contentFolders: () => ipcRenderer.invoke('content:folders'),
  contentAddFolder: () => ipcRenderer.invoke('content:addFolder'),
  contentRemoveFolder: (folder: string) => ipcRenderer.invoke('content:removeFolder', folder),
  localModelsState: () => ipcRenderer.invoke('localmodels:state'),
  localModelDownload: (id: string) => ipcRenderer.invoke('localmodels:download', id),
  localModelCancel: (id: string) => ipcRenderer.invoke('localmodels:cancel', id),
  localModelDelete: (id: string) => ipcRenderer.invoke('localmodels:delete', id),
  localModelSetActive: (id: string | null) => ipcRenderer.invoke('localmodels:setActive', id),
  activityGet: () => ipcRenderer.invoke('activity:get'),
  activitySet: (enabled: boolean) => ipcRenderer.invoke('activity:set', enabled),
  sessionWatchGet: () => ipcRenderer.invoke('sessionwatch:get'),
  sessionWatchSet: (enabled: boolean) => ipcRenderer.invoke('sessionwatch:set', enabled),
  llmWarm: () => ipcRenderer.invoke('localllm:warm'),
  sendFeedback: () => ipcRenderer.invoke('feedback:open'),
  buildPack: (query?: string) => ipcRenderer.invoke('pack:build', query),
  syncStatus: () => ipcRenderer.invoke('sync:status'),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  syncBrief: () => ipcRenderer.invoke('sync:brief'),
  teamJoin: (url: string) => ipcRenderer.invoke('team:join', url),
  githubOpenNew: (name: string) => ipcRenderer.invoke('github:openNew', name),
  githubConnect: (url: string) => ipcRenderer.invoke('github:connect', url),
  importPick: () => ipcRenderer.invoke('import:pick'),
  importScan: (folder: string) => ipcRenderer.invoke('import:scan', folder),
  importRun: (folder: string) => ipcRenderer.invoke('import:run', folder),
  absorbStatus: () => ipcRenderer.invoke('absorb:status'),
  librarianPending: () => ipcRenderer.invoke('librarian:pending'),
  absorbStop: () => ipcRenderer.invoke('absorb:stop'),
  onboardDefaults: () => ipcRenderer.invoke('onboard:defaults'),
  onboardComplete: (payload: OnboardPayload) => ipcRenderer.invoke('onboard:complete', payload),
  enginesDetected: () => ipcRenderer.invoke('engines:isDetected'),
  tourEligible: () => ipcRenderer.invoke('app:tourEligible'),
  appVersion: () => ipcRenderer.invoke('app:version'),
  vaultReady: () => ipcRenderer.invoke('vault:isReady'),
  // Recovery actions for a vault that failed to open (vault:error).
  revealVaultRoot: (root: string) => ipcRenderer.invoke('vault:revealRoot', root),
  relaunch: () => ipcRenderer.invoke('app:relaunch'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateState: () => ipcRenderer.invoke('update:state'),
  searchTemplateLearn: (pasted: string) => ipcRenderer.invoke('search:learn', pasted),
  settingsGet: () => ipcRenderer.invoke('settings:get'),
  settingsSet: (settings: AppSettingsDto) => ipcRenderer.invoke('settings:set', settings),
  mcpInfo: () => ipcRenderer.invoke('mcp:info'),
  mcpConnectDesktop: () => ipcRenderer.invoke('mcp:connectDesktop'),
  mcpConnectCode: () => ipcRenderer.invoke('mcp:connectCode'),
  semanticStatus: () => ipcRenderer.invoke('semantic:status'),
  diagnostics: () => ipcRenderer.invoke('diagnostics:info'),
  exportLogs: () => ipcRenderer.invoke('logs:export'),
  platform: process.platform,
  workspaceList: () => ipcRenderer.invoke('workspace:list'),
  workspaceCreate: (name: string) => ipcRenderer.invoke('workspace:create', { name }),
  workspaceJoin: (name: string, url: string) => ipcRenderer.invoke('workspace:join', { name, url }),
  workspaceSwitch: (id: string) => ipcRenderer.invoke('workspace:switch', id),
  listNotes: () => ipcRenderer.invoke('notes:list'),
  readNote: (id: string) => ipcRenderer.invoke('notes:read', id),
  saveNoteBody: (id: string, body: string) => ipcRenderer.invoke('notes:saveBody', id, body),
  updateMeta: (id: string, patch: MetaPatch) => ipcRenderer.invoke('notes:updateMeta', id, patch),
  verifyNote: (id: string) => ipcRenderer.invoke('notes:verify', id),
  unlinkNote: (fromId: string, toId: string) => ipcRenderer.invoke('notes:unlink', fromId, toId),
  lineageChain: (id: string) => ipcRenderer.invoke('lineage:chain', id),
  readNoteBody: (id: string) => ipcRenderer.invoke('notes:readBody', id),
  listCards: () => ipcRenderer.invoke('cards:list'),
  cardDetail: (id: string) => ipcRenderer.invoke('cards:detail', id),
  approveCard: (id: string, options: ApproveOptionsDto) => ipcRenderer.invoke('cards:approve', id, options),
  rejectCard: (id: string, reason: string) => ipcRenderer.invoke('cards:reject', id, reason),
  capture: (text: string) => ipcRenderer.invoke('capture:text', text),
  captureUndo: (file: string) => ipcRenderer.invoke('capture:undo', file),
  inboxList: () => ipcRenderer.invoke('inbox:list'),
  inboxRetry: () => ipcRenderer.invoke('inbox:retry'),
  sweep: () => ipcRenderer.invoke('sweep:run'),
  subjectKnowledge: () => ipcRenderer.invoke('aliases:knowledge'),
  brainFabric: () => ipcRenderer.invoke('brain:fabric'),
  chatAbort: (channel?: string) => ipcRenderer.invoke('chat:abort', channel),
  chatActive: () => ipcRenderer.invoke('chat:active'),
  chatRoute: (message: string) => ipcRenderer.invoke('chat:route', message),
  errandStart: (goal: string, botId?: string) => ipcRenderer.invoke('errand:start', goal, botId),
  errandAbort: () => ipcRenderer.invoke('errand:abort'),
  errandJournal: () => ipcRenderer.invoke('errand:journal'),
  botsList: () => ipcRenderer.invoke('bots:list'),
  botCreate: (input: { name: string; purpose?: string }) => ipcRenderer.invoke('bots:create', input),
  botDelete: (id: string) => ipcRenderer.invoke('bots:delete', id),
  botTranscript: (id: string) => ipcRenderer.invoke('bots:transcript', id),
  botTaskAdd: (botId: string, input: { name: string; goal: string; schedule?: { days: number[]; hour: number; minute: number }; routineId?: string }) =>
    ipcRenderer.invoke('bots:taskAdd', botId, input),
  botStandingDecline: (botId: string, goal: string) => ipcRenderer.invoke('bots:standingDecline', botId, goal),
  botTaskRemove: (botId: string, taskId: string) => ipcRenderer.invoke('bots:taskRemove', botId, taskId),
  botTaskRan: (botId: string, taskId: string) => ipcRenderer.invoke('bots:taskRan', botId, taskId),
  botsRecommend: () => ipcRenderer.invoke('bots:recommend'),
  botSuggestionDismiss: (name: string) => ipcRenderer.invoke('bots:dismissSuggestion', name),
  botMemory: (botId: string) => ipcRenderer.invoke('bots:memory', botId),
  botMemoryForget: (botId: string, factId: string) => ipcRenderer.invoke('bots:memoryForget', botId, factId),
  errandWallDone: (verdict: 'resolved' | 'skip') => ipcRenderer.invoke('errand:wallDone', verdict),
  routinesList: () => ipcRenderer.invoke('routines:list'),
  routineAdd: (input: { name: string; steps: RoutineStepDto[] }) => ipcRenderer.invoke('routines:add', input),
  routineRemove: (id: string) => ipcRenderer.invoke('routines:remove', id),
  routineRun: (id: string, force?: boolean, slots?: Record<string, string>) =>
    ipcRenderer.invoke('routines:run', id, force, slots),
  routineAbort: () => ipcRenderer.invoke('routines:abort'),
  routineWallDone: (verdict: 'resolved' | 'skip') => ipcRenderer.invoke('routines:wallDone', verdict),
  routineSubmitDone: (verdict: 'approve' | 'always' | 'cancel') => ipcRenderer.invoke('routines:submitDone', verdict),
  pressAskDone: (verdict: 'approve' | 'always' | 'cancel') => ipcRenderer.invoke('press:askDone', verdict),
  approvalsList: () => ipcRenderer.invoke('approvals:list'),
  approvalForget: (fingerprint: string) => ipcRenderer.invoke('approvals:forget', fingerprint),
  agentWatch: (on: boolean) => ipcRenderer.invoke('agent:watch', on),
  agentInput: (input: AgentInputDto) => ipcRenderer.invoke('agent:input', input),
  agentWindow: (show: boolean) => ipcRenderer.invoke('agent:window', show),
  agentGo: (url: string) => ipcRenderer.invoke('agent:go', url),
  agentRefresh: (sharp?: boolean) => ipcRenderer.invoke('agent:refresh', sharp === true),
  agentState: () => ipcRenderer.invoke('agent:state'),
  browsersInstalled: () => ipcRenderer.invoke('browsers:installed'),
  browserChoose: (path: string) => ipcRenderer.invoke('browsers:choose', path),
  browsersList: () => ipcRenderer.invoke('browsers:list'),
  browserImport: (id: string) => ipcRenderer.invoke('browsers:import', id),
  browserForget: () => ipcRenderer.invoke('browsers:forget'),
  browserImportedAt: () => ipcRenderer.invoke('browsers:importedAt'),
  fadingMemories: () => ipcRenderer.invoke('memory:fading'),
  openLoops: () => ipcRenderer.invoke('loops:list'),
  latestBrief: () => ipcRenderer.invoke('brief:latest'),
  refreshBrief: () => ipcRenderer.invoke('brief:refresh'),
  latestDigest: () => ipcRenderer.invoke('digest:latest'),
  search: (query: string, strict?: boolean) => ipcRenderer.invoke('search:query', query, strict),
  engines: () => ipcRenderer.invoke('engines:list'),
  enginesRefresh: () => ipcRenderer.invoke('engines:refresh'),
  engineConnect: (id: 'claude' | 'codex') => ipcRenderer.invoke('engines:connect', id),
  engineDisconnect: (id: 'claude' | 'codex') => ipcRenderer.invoke('engines:disconnect', id),
  engineStates: () => ipcRenderer.invoke('engines:states'),
  onEvent: (listener: (event: EngramEvent) => void) => {
    const wrapped = (_e: unknown, event: EngramEvent) => listener(event)
    ipcRenderer.on('engram:event', wrapped)
    return () => ipcRenderer.removeListener('engram:event', wrapped)
  },
}

contextBridge.exposeInMainWorld('engram', api)
