import { test, expect, _electron as electron, type ElectronApplication, type Page } from '@playwright/test'
import { initVault } from 'core'
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { DevelopersApi, DevUpdate } from '../src/shared/developers.js'
import { filesFixture, consoleFixture } from './developer-workspace-fixture.js'

let app: ElectronApplication, page: Page, project: string
test.describe.configure({ mode: 'serial' })
const tmp = fileURLToPath(new URL('../../../tmp/', import.meta.url))
test.beforeAll(async () => {
  await mkdir(tmp, { recursive: true })
  const vault = await mkdtemp(join(tmp, 'dev-e2e-vault-')), userData = await mkdtemp(join(tmp, 'dev-e2e-data-'))
  project = await mkdtemp(join(tmp, 'dev-e2e-project-'))
  await initVault(vault, { git: false })
  await writeFile(join(project, 'example.ts'), 'export const answer = 42\n')
  app = await electron.launch({ args: [fileURLToPath(new URL('../out/main/index.js', import.meta.url)), '--no-sandbox'], env: { ...process.env, ENGRAM_VAULT: vault, ENGRAM_USERDATA: userData, ENGRAM_NO_GIT: '1', ENGRAM_NO_AUTOTIDY: '1', ENGRAM_ENGINE: 'none', ENGRAM_HIDDEN: '1' } })
  page = await app.firstWindow()
  await expect(page.getByTestId('shell')).toBeVisible()
  await app.evaluate(({ ipcMain }) => {
    ipcMain.removeHandler('accounts:states')
    ipcMain.handle('accounts:states', () => ['claude', 'codex'].map(provider => ({ provider, id: 'system', name: 'System account', installed: true, loggedIn: true, selected: true })))
  })
  await page.setViewportSize({ width: 1360, height: 900 })
})

async function renderTaskFixture() {
  await page.setViewportSize({ width: 1360, height: 900 })
  await page.getByRole('button', { name: 'Developers mode', exact: true }).click()
  const id = await page.evaluate(async () => {
    const api = (window as unknown as { engram: DevelopersApi }).engram, state = await api.devState()
    return (await api.devCreate({ repoId: state.repos[0]!.id, provider: 'codex', model: '', mode: 'review', isolate: false })).id
  })
  await page.locator('.dev-task-link').filter({ hasText: 'New task' }).click()
  await expect(page.getByRole('textbox', { name: 'Development message' })).toBeEnabled()
  const update: DevUpdate = { id, state: 'waiting', runtimeId: 'fixture', usage: { input: 1200, output: 240 }, items: [
    { id: 'request', kind: 'user', text: 'Fix the off-by-one error and add a focused check.' },
    { id: 'command', kind: 'tool', title: 'Command', activity: 'command', text: 'pnpm test\nAll checks passed', status: 'done' },
    { id: 'edit', kind: 'tool', title: 'Edit · example.ts', activity: 'file', text: 'example.ts\n- return items.slice(0, limit + 1)\n+ return items.slice(0, limit)', status: 'running' },
    { id: 'response', kind: 'assistant', text: 'The boundary includes one extra item. The proposed change is:\n\n```ts\nreturn items.slice(0, limit)\n```\n\n| Check | Result |\n| --- | --- |\n| Boundary | Fixed |\n\n1. Preserve the public API.\n2. Add a regression check.' },
  ], pending: [{ id: 'question', kind: 'question', title: 'Your input is needed', detail: '', questions: [{ id: 'scope', text: 'How should a zero limit behave?', options: ['Return an empty list', 'Use the default limit'] }] }] }
  await app.evaluate(({ BrowserWindow }, update) => { BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update }) }, update)
  await expect(page.locator('.dev-message pre code')).toHaveText('return items.slice(0, limit)')
  await expect(page.locator('.dev-message table')).toContainText('Boundary')
  await expect(page.locator('.dev-message ol > li')).toHaveCount(2)
  const reading = await page.locator('.dev-log').evaluate(log => {
    const style = getComputedStyle(log), composer = log.parentElement!.querySelector('.dev-composer')!.getBoundingClientRect()
    return { width: log.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight), composer: composer.width, overflow: log.scrollWidth > log.clientWidth }
  })
  expect(reading.width).toBeLessThanOrEqual(740)
  expect(reading.composer - reading.width).toBeGreaterThanOrEqual(32)
  expect(reading.overflow).toBe(false)
  await expect(page.locator('.dev-tool').first()).toContainText('Done')
  await page.locator('.dev-tool').first().locator('summary').click()
  await expect(page.locator('.dev-tool').first().locator('pre')).toBeVisible()
  await expect(page.locator('.dev-tool').last()).toContainText('Running')
  await page.getByLabel('Return an empty list', { exact: true }).check()
  await page.getByRole('button', { name: 'Session options', exact: true }).click()
  await page.locator('.dev-options-usage > summary').filter({ hasText: 'Usage and limits' }).click()
  await expect(page.getByText('1,200 input · 240 output tokens')).toBeVisible()
  await page.keyboard.press('Escape')
  await screenshot('developers-task-light.png')
  await page.evaluate(() => { document.documentElement.dataset['theme'] = 'dark' })
  await screenshot('developers-task-dark.png')
  await page.evaluate(() => { document.documentElement.dataset['theme'] = 'light' })
  await app.evaluate(({ BrowserWindow, ipcMain }, id) => {
    BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id, state: 'idle', items: [], pending: [], usage: {} } })
    ipcMain.removeHandler('devFork')
    ipcMain.handle('devFork', (_event, _id, isolate) => { if (isolate !== true) throw new Error('Wrong branch option'); throw new Error('A separate worktree needs a Git repository with at least one commit. Choose “Same folder” to branch only the conversation. No files were changed.') })
  }, id)
  await page.getByRole('button', { name: 'Branch session', exact: true }).click()
  await expect(page.getByRole('button', { name: /Same folder/ })).toBeVisible()
  await screenshot('developers-branch-options.png')
  await page.getByRole('button', { name: /Separate worktree.*Isolated files/ }).click()
  await expect(page.getByRole('alert')).toContainText('needs a Git repository')
  await expect(page.getByRole('alert')).not.toContainText('Error invoking remote method')
  await page.getByRole('button', { name: 'Dismiss error' }).click()
  await page.setViewportSize({ width: 950, height: 900 })
  const narrow = await page.locator('.dev-log').evaluate(log => {
    const style = getComputedStyle(log), composer = log.parentElement!.querySelector('.dev-composer')!.getBoundingClientRect()
    return { width: log.clientWidth - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight), composer: composer.width, overflow: log.scrollWidth > log.clientWidth }
  })
  expect(narrow.composer - narrow.width).toBeGreaterThanOrEqual(32)
  expect(narrow.overflow).toBe(false)
  await screenshot('developers-reading-narrow.png')
}
test.afterAll(async () => { await app?.close() })
async function screenshot(file: string) {
  await page.evaluate(() => { for (const animation of document.getAnimations()) if (animation.effect?.getTiming().iterations !== Infinity) animation.finish() })
  const png = await app.evaluate(async ({ BrowserWindow }) => {
    const window = BrowserWindow.getAllWindows().find(one => one.webContents.getURL().includes('index.html'))!
    await window.webContents.capturePage()
    await new Promise(resolve => setTimeout(resolve, 400))
    return (await window.webContents.capturePage()).toPNG().toString('base64')
  })
  await writeFile(join(tmp, file), Buffer.from(png, 'base64'))
}
test('developer workspace is opt-in, keeps normal chats separate and groups developer settings', async () => {
  await page.getByRole('button', { name: 'Developers mode', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Code, in conversation' })).toBeVisible()
  await page.getByRole('button', { name: 'Enable Developers', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Choose your first project' })).toBeVisible()
  await app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }) }, project)
  await page.getByRole('button', { name: 'Add folder', exact: true }).click()
  await expect(page.locator('.dev-folder-button')).toHaveCount(1)
  await expect(page.getByTestId('app-sidebar')).toBeVisible()
  await expect(page.locator('.sidebar-status-block')).toBeVisible()
  await expect(page.locator('.recent-web')).toHaveCount(0)
  await expect(page.locator('.dev-composer select')).toHaveCount(0)
  const welcome = await page.locator('.dev-empty').boundingBox(), entry = await page.locator('.dev-composer').boundingBox()
  expect(Math.abs(welcome!.x + welcome!.width / 2 - entry!.x - entry!.width / 2)).toBeLessThan(2)
  expect(entry!.y - welcome!.y - welcome!.height).toBeLessThan(36)
  await expect(page.locator('.dev-header')).toHaveCSS('box-shadow', 'none')
  await expect(page.locator('.dev-header')).toHaveCSS('border-bottom-width', '0px')
  await expect(page.getByRole('button', { name: 'Developers mode', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Chat mode', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Skills', exact: true })).toHaveCount(0)
  await app.evaluate(({ ipcMain }) => { ipcMain.removeHandler('devProjectCommands'); ipcMain.handle('devProjectCommands', () => [{ name: 'review', description: 'Review a change', prompt: '$review ' }, { name: 'test', description: 'Run focused checks', prompt: '$test ' }]) })
  const composer = page.getByRole('textbox', { name: 'Development message' })
  await composer.fill('/')
  await expect(page.getByRole('listbox', { name: 'Skills' })).toBeVisible()
  await screenshot('developers-slash.png')
  await composer.press('ArrowDown'); await composer.press('Enter')
  await expect(composer).toHaveValue('$test ')
  await expect(page.getByRole('listbox', { name: 'Skills' })).toHaveCount(0)
  await composer.fill('/'); await composer.press('Escape')
  await expect(page.getByRole('listbox', { name: 'Skills' })).toHaveCount(0)
  await composer.fill(''); await composer.fill('/')
  await expect(page.getByRole('listbox', { name: 'Skills' })).toBeVisible()
  await composer.fill('')
  await page.getByRole('button', { name: 'Task access', exact: true }).click()
  await expect(page.locator('.dev-popover')).toHaveCSS('animation-name', 'dev-popover-in')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.dev-popover')).toHaveCSS('animation-name', 'none')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.getByRole('radio', { name: /Full access/ }).check()
  await expect(page.getByLabel('I allow commands and file changes without approval.')).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await page.getByTestId('activity-settings').click()
  await expect(page.getByTestId('settings-nav-developers')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('setting-session-watch')).not.toBeChecked()
  await expect(page.getByText('Connected accounts', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Repositories', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Open Developers', exact: true })).toHaveCount(0)
  await screenshot('developers-settings.png')
  await page.keyboard.press('Escape')
  const workspace = await page.getByTestId('developers-view').boundingBox(), canvas = await page.locator('.canvas').boundingBox()
  expect(workspace?.width).toBe(canvas?.width)
  await screenshot('developers-workspace.png')
  const composerAlignment = await page.locator('.dev-composer').evaluate(composer => {
    const send = composer.querySelector('.dev-send')!.getBoundingClientRect(), options = composer.querySelector('[aria-label="Session options"]')!.getBoundingClientRect()
    const access = composer.querySelector('[aria-label="Task access"]')!.getBoundingClientRect()
    return { right: Math.abs(send.y + send.height / 2 - options.y - options.height / 2), left: Math.abs(access.y + access.height / 2 - options.y - options.height / 2) }
  })
  expect(composerAlignment.right).toBeLessThan(2)
  expect(composerAlignment.left).toBeLessThan(2)
  await page.setViewportSize({ width: 600, height: 850 })
  await page.getByTestId('app-sidebar-close').click()
  await expect(page.getByRole('textbox', { name: 'Development message' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await screenshot('developers-narrow.png')
  await page.getByTestId('app-sidebar-open').click()
  await page.getByRole('button', { name: 'Chat mode', exact: true }).click()
  await expect(page.getByTestId('developers-view')).toHaveCount(0)
})

async function historyFixture() {
  await page.setViewportSize({ width: 1360, height: 900 })
  const before = await page.evaluate(() => (window as unknown as { engram: { settingsGet(): Promise<{ codexModel?: string; codexEffort?: string }> } }).engram.settingsGet())
  const session = await page.evaluate(async () => {
    const api = (window as unknown as { engram: DevelopersApi }).engram, state = await api.devState()
    return api.devCreate({ repoId: state.repos[0]!.id, provider: 'codex', model: 'fixture-model', mode: 'review', isolate: false })
  })
  session.title = 'Imported conversation'
  session.items = [{ id: 'prior-user', kind: 'user', text: 'Earlier saved question' }, { id: 'prior-answer', kind: 'assistant', text: 'Earlier saved answer' }]
  await app.evaluate(({ ipcMain }, session) => {
    ipcMain.removeHandler('devExternal'); ipcMain.handle('devExternal', () => [{ id: 'previous', title: session.title, provider: 'codex', cwd: session.cwd, updatedAt: Date.now() }])
    let failed = false
    ipcMain.removeHandler('devExternalRead'); ipcMain.handle('devExternalRead', () => { if (!failed) { failed = true; throw new Error('The development response exceeded the size limit.') } return session.items })
    ipcMain.removeHandler('devCreate'); ipcMain.handle('devCreate', () => session)
    ipcMain.removeHandler('devSession'); ipcMain.handle('devSession', () => session)
    ipcMain.removeHandler('models:list'); ipcMain.handle('models:list', () => [{ value: 'fixture-model', label: 'Fixture model', detail: 'Test catalog', efforts: ['low', 'medium', 'high'] }])
  }, session)
  await app.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'models:changed' }) })
  await page.getByRole('button', { name: /^Project options for/ }).click()
  await page.getByRole('button', { name: 'Previous sessions', exact: true }).click()
  await page.getByRole('button', { name: 'Imported conversation' }).click()
  await expect(page.getByRole('alert')).toContainText('Could not load this session')
  await expect(page.getByRole('button', { name: 'Resume session', exact: true })).toBeDisabled()
  await screenshot('developers-history-error.png')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Saved session preview' }).getByText('Earlier saved answer')).toBeVisible()
  await screenshot('developers-history.png')
  const aligned = await page.locator('.dev-history-dialog > footer label').evaluate(label => {
    const box = label.querySelector('input')!.getBoundingClientRect(), text = label.querySelector('span')!.getBoundingClientRect()
    return Math.abs(box.y + box.height / 2 - text.y - text.height / 2) < 3
  })
  expect(aligned).toBe(true)
  await expect(page.getByRole('button', { name: 'Resume session', exact: true })).toBeDisabled()
  await page.getByLabel('I have stopped this session in other apps.').check()
  await page.getByRole('button', { name: 'Resume session', exact: true }).click()
  await expect(page.locator('.dev-log').getByText('Earlier saved question')).toBeVisible()
  await expect(page.locator('.dev-log').getByText('Earlier saved answer')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Choose session', exact: true })).toHaveCount(0)
  await expect(page.locator('.dev-heading h2')).toHaveText('Imported conversation')
  await page.getByTestId('developers-view').getByTestId('model-picker').click()
  await expect(page.getByTestId('provider-pick-claude')).toBeEnabled()
  await expect(page.getByTestId('model-pick-fixture-model')).toBeVisible()
  await screenshot('developers-models.png')
  await expect(page.locator('.dev-effort-scale')).toBeVisible()
  await expect(page.getByTestId('effort-pick-high')).toBeVisible()
  await screenshot('developers-effort.png')
  await page.getByTestId('effort-pick-high').click()
  await expect(page.getByTestId('model-picker-menu')).not.toBeVisible()
  await expect(page.getByTestId('developers-view').getByTestId('effort-picker')).toHaveCount(0)
  await page.getByTestId('developers-view').getByTestId('model-picker').click()
  await expect(page.getByTestId('effort-pick-high')).toHaveAttribute('aria-checked', 'true')
  await page.keyboard.press('Escape')
  const after = await page.evaluate(() => (window as unknown as { engram: { settingsGet(): Promise<{ codexModel?: string; codexEffort?: string }> } }).engram.settingsGet())
  expect(after.codexModel).toBe(before.codexModel)
  expect(after.codexEffort).toBe(before.codexEffort)
}
test('renders structured questions, code and task usage in light and dark layouts', renderTaskFixture)

test('project sessions split independently and drafts survive switching modes', async () => {
  await page.setViewportSize({ width: 1360, height: 900 })
  await page.getByRole('button', { name: '2 panes', exact: true }).click()
  const panes = page.locator('.dev-pane')
  await expect(panes).toHaveCount(2)
  await panes.nth(1).getByRole('textbox', { name: 'Development message' }).fill('Second pane draft')
  await page.getByRole('button', { name: 'Chat mode', exact: true }).click()
  await page.getByRole('button', { name: 'Developers mode', exact: true }).click()
  await expect(panes.nth(1).getByRole('textbox', { name: 'Development message' })).toHaveValue('Second pane draft')
  await panes.nth(1).getByRole('button', { name: 'Choose conversation for this pane' }).click()
  await page.getByRole('searchbox', { name: 'Search project sessions' }).fill('New task')
  await screenshot('developers-pane-picker.png')
  await page.getByRole('dialog', { name: 'Choose conversation for this pane' }).getByRole('button', { name: 'New task', exact: true }).click()
  await expect(panes.nth(1).locator('.dev-heading h2')).toHaveText('New task')
  await expect(panes.nth(0).getByRole('textbox', { name: 'Development message' })).toBeEnabled()
  await panes.nth(1).getByRole('button', { name: 'Choose conversation for this pane' }).click()
  await page.getByRole('searchbox', { name: 'Search project sessions' }).fill('')
  await page.getByRole('dialog', { name: 'Choose conversation for this pane' }).getByRole('button', { name: 'New session', exact: true }).click()
  await expect(panes.nth(1).getByRole('textbox', { name: 'Development message' })).toHaveValue('Second pane draft')
  const wide = await panes.evaluateAll(nodes => nodes.map(node => ({ x: node.getBoundingClientRect().x, y: node.getBoundingClientRect().y })))
  expect(wide[0]!.y).toBe(wide[1]!.y); expect(wide[0]!.x).toBeLessThan(wide[1]!.x)
  await screenshot('developers-split-wide.png')
  await page.setViewportSize({ width: 760, height: 1000 })
  await page.getByTestId('app-sidebar-close').click()
  const narrow = await panes.evaluateAll(nodes => nodes.map(node => ({ x: node.getBoundingClientRect().x, y: node.getBoundingClientRect().y })))
  expect(narrow[0]!.x).toBe(narrow[1]!.x); expect(narrow[0]!.y).toBeLessThan(narrow[1]!.y)
  await screenshot('developers-split-narrow.png')
  await page.getByRole('button', { name: '4 panes', exact: true }).click()
  await expect(panes).toHaveCount(4)
  await page.getByRole('button', { name: 'Single conversation', exact: true }).click()
  await expect(panes).toHaveCount(1)
  await page.getByTestId('app-sidebar-open').click()
  await page.locator('.dev-folder-button').click()
  await expect(page.locator('.dev-task-link')).toHaveCount(0)
  await page.locator('.dev-folder-button').click()
  await expect(page.locator('.dev-task-link')).toHaveCount(1)
})

test('switches providers from the same task composer and retains its folder and conversation', async () => {
  await page.setViewportSize({ width: 1360, height: 900 })
  await app.evaluate(({ ipcMain, BrowserWindow }) => {
    const engines = ['claude', 'codex'].map(id => ({ id, installed: true, loggedIn: true }))
    ipcMain.removeHandler('engines:states'); ipcMain.handle('engines:states', () => engines)
    BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'engines:changed', engines })
  })
  const session = await page.evaluate(async () => {
    const state = await window.engram.devState()
    return window.engram.devCreate({ repoId: state.repos[0]!.id, provider: 'codex', model: '', mode: 'review', isolate: false })
  })
  await page.locator('.dev-task-link').last().click()
  const picker = page.getByTestId('developers-view').getByTestId('model-picker')
  await picker.click(); await page.getByTestId('provider-pick-claude').click()
  await expect(page.locator('.dev-message-notice')).toContainText('ChatGPT → Claude')
  await expect(picker.locator('[data-provider="claude"]')).toHaveCount(1)
  await page.getByTestId('provider-pick-codex').click()
  await expect(page.locator('.dev-message-notice').last()).toContainText('Claude → ChatGPT')
  await page.keyboard.press('Escape')
  const after = await page.evaluate(id => window.engram.devSession(id), session.id)
  expect(after.id).toBe(session.id); expect(after.cwd).toBe(session.cwd)
  expect(after.provider).toBe('codex'); expect(after.runtimeId).toBeUndefined()
})

test('previous-session preview continues with visible history and task-scoped model controls', historyFixture)

test('project files preserve drafts, reject external edit conflicts and attach selected context', () => filesFixture({ app, page, project, screenshot }))
test('command console executes, retains output and cancels its owned process', () => consoleFixture({ app, page, project, screenshot }))
test('preloads both connected accounts without selecting a provider or starting a task', async () => {
  await app.evaluate(({ ipcMain, BrowserWindow }) => {
    const engines = [{ id: 'claude', installed: true, loggedIn: true }, { id: 'codex', installed: true, loggedIn: true }]
    ipcMain.removeHandler('engines:states'); ipcMain.handle('engines:states', () => engines)
    ipcMain.removeHandler('devUsage'); ipcMain.handle('devUsage', (_event, provider) => ({ windows: [{ name: `${provider} fixture limit`, used: provider === 'claude' ? 25 : 40 }], updatedAt: Date.now() }))
    BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'engines:changed', engines })
  })
  await page.getByRole('button', { name: 'Session options', exact: true }).click()
  await page.locator('.dev-options-usage > summary').filter({ hasText: 'Usage and limits' }).click()
  await expect(page.getByText('claude fixture limit')).toBeVisible()
  await expect(page.getByText('codex fixture limit')).toBeVisible()
  await expect(page.getByText('75% remaining')).toBeVisible()
  await expect(page.getByText('60% remaining')).toBeVisible()
  await app.evaluate(({ BrowserWindow }) => {
    BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id: 'usage-only', provider: 'codex', state: 'running', items: [], pending: [], usage: { windows: [{ name: 'codex fixture limit', used: 70 }], updatedAt: Date.now() } } })
  })
  await expect(page.getByText('30% remaining')).toBeVisible()
  await screenshot('developers-account-usage.png')
  await page.keyboard.press('Escape')
})

test('connected accounts switch without restarting and keep per-account limits', async () => {
  const pid = app.process().pid
  await app.evaluate(({ ipcMain }) => {
    ipcMain.removeHandler('accounts:states')
    ipcMain.handle('accounts:states', async event => {
      const profiles = await event.sender.executeJavaScript('window.engram.accountProfiles()')
      return [{ id: 'system', provider: 'claude', name: 'System account' }, { id: 'system', provider: 'codex', name: 'System account' }, ...profiles.profiles].map(row => ({ ...row, installed: true, loggedIn: true, selected: profiles.selected[row.provider] === row.id }))
    })
    ipcMain.removeHandler('devUsage')
    ipcMain.handle('devUsage', (_event, provider, profile) => ({ windows: [{ name: `${provider} ${profile === 'system' ? 'personal' : 'work'} limit`, used: profile === 'system' ? 20 : 65 }], updatedAt: Date.now() }))
  })
  await page.getByTestId('activity-settings').click()
  await page.getByTestId('settings-nav-ai').click()
  await expect(page.getByTestId('brain-claude-status')).toHaveText('Connected')
  const card = await page.getByRole('region', { name: 'Claude connection', exact: true }).boundingBox()
  expect(card!.height).toBeLessThan(100)
  await screenshot('developers-connections.png')
  await page.getByTestId('settings-view').getByRole('button', { name: 'Manage ChatGPT accounts', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Account profiles' })).toBeVisible()
  await page.getByLabel('New account label').fill('Work account')
  await page.getByRole('button', { name: 'Add account', exact: true }).click()
  const work = page.getByRole('region', { name: 'Work account', exact: true })
  await expect(work.getByRole('button', { name: 'Use account', exact: true })).toBeEnabled()
  await expect(work.getByText('35% remaining')).toBeVisible()
  await screenshot('developers-profiles.png')
  const bounds = await page.getByRole('dialog', { name: 'Account profiles' }).boundingBox()
  expect(Math.abs(bounds!.x + bounds!.width / 2 - page.viewportSize()!.width / 2)).toBeLessThan(2)
  await work.getByRole('button', { name: 'Use account', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Account profiles' })).not.toBeVisible()
  expect(app.process().pid).toBe(pid)
  await page.getByTestId('settings-view').getByRole('button', { name: 'Manage ChatGPT accounts', exact: true }).click()
  await expect(work.getByRole('button', { name: 'Current', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Account profiles' }).getByRole('region', { name: 'System account', exact: true }).getByRole('button', { name: 'Use account', exact: true }).click()
  await page.keyboard.press('Escape')
})

test('Stop remains available while an existing task is still connecting', async () => {
  await page.getByRole('textbox', { name: 'Development message' }).fill('Inspect without changing files')
  await app.evaluate(({ ipcMain }) => {
    let release: (() => void) | undefined
    ipcMain.removeHandler('devSend')
    ipcMain.handle('devSend', async (event, id) => {
      event.sender.send('engram:event', { type: 'dev:changed', update: { id, state: 'starting', items: [], pending: [], usage: {} } })
      await new Promise<void>(resolve => { release = resolve })
    })
    ipcMain.removeHandler('devStop')
    ipcMain.handle('devStop', (event, id) => {
      event.sender.send('engram:event', { type: 'dev:changed', update: { id, state: 'idle', items: [], pending: [], usage: {} } })
      release?.()
    })
  })
  await page.getByRole('button', { name: 'Send development message', exact: true }).click()
  const stop = page.getByRole('button', { name: 'Stop development task', exact: true })
  await expect(stop).toBeEnabled()
  await stop.click()
  await expect(page.getByRole('textbox', { name: 'Development message' })).toBeEnabled()
  await expect(page.getByText('Connecting…', { exact: true })).toHaveCount(0)
})

test('retains live updates arriving while a conversation snapshot is loading', async () => {
  const snapshot = await page.evaluate(async () => {
    const state = await window.engram.devState()
    return window.engram.devSession(state.sessions.at(-1)!.id)
  })
  await app.evaluate(({ ipcMain }, snapshot) => {
    ipcMain.removeHandler('devSession')
    ipcMain.handle('devSession', async event => {
      await new Promise(resolve => setTimeout(resolve, 200))
      event.sender.send('engram:event', { type: 'dev:changed', update: { id: snapshot.id, state: 'idle', items: [{ id: 'during-load', kind: 'assistant', text: 'Completed while the conversation was loading' }], pending: [], usage: {} } })
      await new Promise(resolve => setTimeout(resolve, 200))
      return snapshot
    })
  }, snapshot)
  await page.getByRole('button', { name: 'Chat mode', exact: true }).click()
  await page.getByRole('button', { name: 'Developers mode', exact: true }).click()
  await expect(page.locator('.dev-log').getByText('Completed while the conversation was loading', { exact: true })).toBeVisible()
})
