import { expect, type ElectronApplication, type Page } from '@playwright/test'

export async function queueFixture({ app, page, screenshot }: { app: ElectronApplication; page: Page; screenshot(file: string): Promise<void> }) {
  const id = await page.evaluate(async () => (await window.engram.devState()).sessions.at(-1)!.id)
  await app.evaluate(({ ipcMain, BrowserWindow }, id) => {
    let outbox: { id: string; text: string; state: 'queued' }[] = []
    const publish = () => BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id, provider: 'codex', state: 'running', items: [], pending: [], usage: {}, outbox } })
    ipcMain.removeHandler('devFollowup'); ipcMain.removeHandler('devQueued')
    ipcMain.handle('devFollowup', (_event, _id, text, mode) => {
      if (_id !== id) throw new Error('Wrong session')
      if (mode === 'queue') outbox.push({ id: String(outbox.length), text, state: 'queued' })
      else if (mode !== 'steer') throw new Error('Wrong delivery mode')
      publish()
    })
    ipcMain.handle('devQueued', (_event, _id, messageId, action, text) => {
      if (action === 'remove') outbox = outbox.filter(value => value.id !== messageId)
      else if (action === 'edit') outbox.find(value => value.id === messageId)!.text = text
      publish()
    })
    publish()
  }, id)
  const input = page.getByRole('textbox', { name: 'Development message' })
  await expect(input).toBeEnabled()
  await input.fill('Follow up after this turn')
  await input.press('Enter')
  const queue = page.getByRole('region', { name: 'Queued messages' })
  await expect(queue).toContainText('Follow up after this turn')
  await queue.getByRole('button', { name: 'Edit queued message' }).click()
  await queue.getByRole('textbox', { name: 'Edit queued message' }).fill('Updated follow-up')
  await queue.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(queue).toContainText('Updated follow-up')
  await input.fill('Focus on tests now')
  await page.mouse.move(400, 200)
  await screenshot('developers-steer-wide.png')
  await page.setViewportSize({ width: 600, height: 850 })
  await page.getByTestId('app-sidebar-close').click()
  expect(await page.locator('.dev-composer').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await screenshot('developers-steer-narrow.png')
  await page.setViewportSize({ width: 1360, height: 900 })
  await page.getByTestId('app-sidebar-open').click()
  await page.getByRole('button', { name: 'Steer', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Stop development task' })).toBeEnabled()
  await screenshot('developers-queue.png')
  await queue.getByRole('button', { name: 'Remove queued message' }).click()
  await expect(queue).toHaveCount(0)
  await app.evaluate(({ BrowserWindow }, id) => BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id, provider: 'claude', state: 'running', items: [], pending: [], usage: {} } }), id)
  await input.fill('Claude next turn')
  await expect(page.getByRole('button', { name: 'Steer', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Queue development message' })).toBeEnabled()
  await input.fill('')
  await app.evaluate(({ BrowserWindow }, id) => BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id, state: 'running', items: [{ id: 'delivery-fixture', kind: 'user', text: 'Unconfirmed fixture message', status: 'failed' }], pending: [], usage: {} } }), id)
  const delivery = page.locator('.dev-message-user').last()
  await expect(delivery).toContainText('Delivery not confirmed')
  const alignment = await delivery.evaluate(node => ({ bubble: node.querySelector('div')!.getBoundingClientRect().bottom, status: node.querySelector('small')!.getBoundingClientRect().top }))
  expect(alignment.status).toBeGreaterThanOrEqual(alignment.bubble)
  await screenshot('developers-delivery-status.png')
  await app.evaluate(({ BrowserWindow }, id) => BrowserWindow.getAllWindows()[0]!.webContents.send('engram:event', { type: 'dev:changed', update: { id, provider: 'codex', state: 'idle', items: [], pending: [], usage: {} } }), id)

}
