import { describe, expect, it, vi } from 'vitest'
import { isOfficeTool, officeStepSummary, officeTools, type OfficeOp } from '../src/office-tools.js'

const CONTEXT = { task: 'work in Office' }
function setup() {
  const calls: { op: OfficeOp; args: Record<string, unknown> }[] = []
  const run = vi.fn(async (op: OfficeOp, args: Record<string, unknown>) => { calls.push({ op, args }); return { echoed: op } })
  const tools = officeTools({ run })
  // A tool validates its arguments synchronously before it ever returns a
  // promise; wrapping the call turns that early throw into a rejection the
  // test can await, exactly as the agent loop's own try/catch would see it.
  const invoke = (name: string, args: unknown) => (async () => tools.find((one) => one.name === name)!.run((name === 'excel_read' || name === 'excel_write') ? { workbook: 'Book1', sheet: 'Sheet1', ...args as object } : args as Record<string, unknown>, CONTEXT))()
  const tool = (name: string) => ({ run: (args: unknown) => invoke(name, args) })
  return { calls, run, tools, tool }
}

describe('office tool surface', () => {
  it('offers exactly the four apps and marks them as office tools', () => {
    const { tools } = setup()
    expect(tools.map((t) => t.name)).toEqual(['excel_workbooks', 'excel_read', 'excel_write', 'outlook_mail', 'outlook_read', 'outlook_draft', 'outlook_calendar', 'word_write', 'ppt_build'])
    expect(tools.every((t) => isOfficeTool(t.name))).toBe(true)
    expect(isOfficeTool('search_web')).toBe(false)
  })
})

describe('excel_write validation and dispatch', () => {
  it('writes clean cells and only saves when told', async () => {
    const { tool, calls } = setup()
    await tool('excel_write').run({ cells: [{ cell: 'B2', value: 23.5 }, { cell: 'C2', value: '=SUM(A1:A3)' }], saveAs: 'C:\\out\\x.xlsx' })
    expect(calls[0]!.op).toBe('excel.write')
    expect(calls[0]!.args).toMatchObject({ cells: [{ cell: 'B2', value: 23.5 }, { cell: 'C2', value: '=SUM(A1:A3)' }], saveAs: 'C:\\out\\x.xlsx' })
    expect(calls[0]!.args['save']).toBeUndefined()
  })

  it.each([
    { args: { cells: [{ cell: 'ZZ99', value: 1 }] }, throws: false },
    { args: { cells: [{ cell: 'nope', value: 1 }] }, throws: true },
    { args: { cells: [{ cell: 'B2', value: { a: 1 } }] }, throws: true },
    { args: { cells: [] }, throws: true },
    { args: { cells: [{ cell: 'B2', value: 1 }], extra: true }, throws: true },
  ])('guards the cell shape (%#)', async ({ args, throws }) => {
    const { tool, run } = setup()
    if (throws) { await expect(tool('excel_write').run(args)).rejects.toThrow(); expect(run).not.toHaveBeenCalled() }
    else { await tool('excel_write').run(args); expect(run).toHaveBeenCalledOnce() }
  })

  it('rejects a range that is not a range for excel_read', async () => {
    const { tool, run } = setup()
    await expect(tool('excel_read').run({ range: 'not a range' })).rejects.toThrow('A1')
    await tool('excel_read').run({ range: 'A1:D20', sheet: 'Sheet1' })
    expect(run).toHaveBeenCalledWith('excel.read', { workbook: 'Book1', range: 'A1:D20', sheet: 'Sheet1' }, undefined)
  })
})

describe('outlook_draft never sends and needs a recipient or a reply target', () => {
  it('passes a new draft through', async () => {
    const { tool, calls } = setup()
    await tool('outlook_draft').run({ to: 'a@b.com', subject: 'Hi', body: 'text' })
    expect(calls[0]!.op).toBe('outlook.draft')
    expect(calls[0]!.args).toMatchObject({ to: 'a@b.com', subject: 'Hi', body: 'text' })
  })
  it('accepts a reply by id', async () => {
    const { tool, calls } = setup()
    await tool('outlook_draft').run({ replyTo: 'ENTRY-ID', replyAll: true, body: 'ok' })
    expect(calls[0]!.args).toMatchObject({ replyTo: 'ENTRY-ID', replyAll: true })
  })
  it('refuses a draft with neither to nor replyTo', async () => {
    const { tool, run } = setup()
    await expect(tool('outlook_draft').run({ body: 'text' })).rejects.toThrow('needs to')
    expect(run).not.toHaveBeenCalled()
  })
})

describe('ppt_build audits before it touches PowerPoint', () => {
  it('returns the audit and never calls the courier when the deck reads dirty', async () => {
    const { tool, run } = setup()
    const out = await tool('ppt_build').run({ slides: [{ title: 'TODO', bullets: ['This deck was generated by an AI.'] }] })
    expect(out).toContain('does not read clean')
    expect(run).not.toHaveBeenCalled()
  })
  it('builds a clean deck', async () => {
    const { tool, calls } = setup()
    await tool('ppt_build').run({ slides: [{ title: 'Plan', subtitle: 'Q4' }, { title: 'Steps', bullets: ['Ship', 'Measure'] }], saveAs: 'C:\\d.pptx' })
    expect(calls[0]!.op).toBe('ppt.build')
    expect(calls[0]!.args['slides']).toHaveLength(2)
    expect(calls[0]!.args['saveAs']).toBe('C:\\d.pptx')
  })
})

describe('word_write blocks', () => {
  it('takes headings, paragraphs and bullets; rejects an unknown kind', async () => {
    const { tool, calls, run } = setup()
    await tool('word_write').run({ blocks: [{ kind: 'heading', text: 'A' }, { kind: 'bullets', items: ['x', 'y'] }] })
    expect(calls[0]!.args['blocks']).toHaveLength(2)
    await expect(tool('word_write').run({ blocks: [{ kind: 'quote', text: 'x' }] })).rejects.toThrow()
    expect(run).toHaveBeenCalledOnce()
  })
})

describe('officeStepSummary', () => {
  it('names the visible move', () => {
    expect(officeStepSummary('excel_write', { cells: [1, 2, 3] })).toBe('write 3 cells in Excel')
    expect(officeStepSummary('outlook_draft', { replyTo: 'x' })).toBe('draft a reply in Outlook')
    expect(officeStepSummary('ppt_build', { slides: [1, 2] })).toBe('build 2 slides in PowerPoint')
    expect(officeStepSummary('search_web', {})).toBeNull()
  })
})

describe('office safety regressions', () => {
  it('requires a stable workbook and sheet before any read or write', async () => {
    const { tools, run } = setup()
    for (const name of ['excel_read', 'excel_write']) {
      const tool = tools.find((t) => t.name === name)!
      for (const target of [{}, { workbook: 'Book1' }, { sheet: 'Sheet1' }]) {
        await expect((async () => tool.run({ ...target, ...(name === 'excel_read' ? { range: 'A1' } : { cells: [{ cell: 'A1', value: 1 }] }) }, CONTEXT))()).rejects.toThrow('explicitly')
      }
    }
    expect(run).not.toHaveBeenCalled()
  })
  it.each(['A1:XFD1048576', 'A0', 'XFE1', 'A1048577', 'A1:A4001'])('rejects unsafe ranges before dispatch: %s', async (range) => {
    const { tool, run } = setup()
    await expect(tool('excel_read').run({ range })).rejects.toThrow()
    expect(run).not.toHaveBeenCalled()
  })
  it.each(['=WEBSERVICE("https://example.invalid/")', '=SUM([other.xlsx]Sheet1!A1)', '=HYPERLINK("https://example.invalid")'])('rejects external formulas: %s', async (value) => {
    const { tool, run } = setup()
    await expect(tool('excel_write').run({ cells: [{ cell: 'A1', value }] })).rejects.toThrow()
    expect(run).not.toHaveBeenCalled()
  })
  it('rejects oversized chart and format ranges', async () => {
    const { tool, run } = setup()
    for (const part of [{ formats: [{ range: 'A1:XFD1048576' }] }, { charts: [{ data: 'A1:XFD1048576' }] }]) {
      await expect(tool('excel_write').run({ cells: [], ...part })).rejects.toThrow('4000')
    }
    expect(run).not.toHaveBeenCalled()
  })
})
