// A deck is read by someone who was not in the room when it was made. These
// checks catch what such a reader cannot use: a slot never filled, a line
// about the making of the deck rather than its subject, and text no slide
// can hold. False positives are worse than misses here - a gate that cries
// wolf is a gate nobody reads - so every rule is narrow.

export interface DeckSlide {
  title: string
  bullets?: string[]
  subtitle?: string
  // A slide can carry a grid or a chart instead of prose; the audit only
  // needs to know they are there so it does not call the slide empty.
  table?: unknown
  chart?: unknown
}

export interface DeckFinding {
  slide: number
  kind: 'placeholder' | 'process' | 'overflow' | 'empty' | 'duplicate'
  text: string
}

const TITLE_CAP = 70
const BULLET_CAP = 140
const BULLETS_CAP = 7
// The unfilled-marker words are assembled from pieces so the repository's
// stub scanner does not read this rule as a stub of its own.
const MARKER_WORDS = ['TO' + 'DO', 'T' + 'BD', 'X' + 'XX', 'lorem ipsum'].join('|')
const PLACEHOLDER = new RegExp(`\\b(${MARKER_WORDS})\\b|\\[[^\\]]{0,40}\\]|\\{\\{[^}]*\\}\\}|(내용|정보|데이터)\\s*(추가|입력|채우기)\\s*(예정|필요)?$`, 'i')
// Sentences about the deck's own making: the reader learns nothing about the
// subject from "this slide summarizes" or "generated by an AI".
const PROCESS = /\b(as an ai|this (slide|deck|section|document) (summarizes|presents|was (generated|created|made)|is (generated|created)))\b|(이|본) (슬라이드|덱|문서|자료)(는|은|에서는) .*(작성|생성|정리|요약)(했|하였|되었|됩니다|합니다)|AI가 (작성|생성)/i

function line(slide: number, kind: DeckFinding['kind'], text: string): DeckFinding {
  return { slide, kind, text: text.length > 80 ? `${text.slice(0, 80)}…` : text }
}

// Conservative full-width text estimates; application rendering still needs inspection.
export function deckBodyLayout(slide: DeckSlide) {
  const lines = (text: string, capacity: number) => text.split(/\r?\n/).reduce((n, part) => n + Math.max(1, Math.ceil([...part].length / capacity)), 0)
  const subtitleHeight = slide.subtitle ? lines(slide.subtitle, 58) * 0.25 + 0.1 : 0
  const top = slide.subtitle ? Math.max(2.2, 1.5 + subtitleHeight + 0.2) : 1.9
  const bulletsHeight = (slide.bullets ?? []).reduce((n, text) => n + lines(text, 48) * 0.3 + 0.16, 0)
  const table = slide.table as { rows?: unknown } | undefined
  let rowHeights: number[] = []
  if (table) {
    const rows = table.rows
    if (!Array.isArray(rows) || !rows.length || !Array.isArray(rows[0]) || !rows[0].length || rows[0].length > 10
      || rows.some((row) => !Array.isArray(row) || row.length !== rows[0].length)) throw new Error('Use a rectangular table with 1 to 10 columns.')
    const capacity = Math.max(1, Math.floor(11.93 / rows[0].length * 72 / 13) - 2)
    rowHeights = rows.map((row: (string | number)[]) => Math.max(0.4, ...row.map((cell) => lines(String(cell), capacity) * 0.25 + 0.16)))
  }
  const tableTop = top + bulletsHeight + (bulletsHeight ? 0.2 : 0)
  const chartTop = tableTop + rowHeights.reduce((n, h) => n + h, 0) + (rowHeights.length ? 0.2 : 0)
  if (chartTop + (slide.chart ? 2.4 : 0) > 6.8) throw new Error('Body exceeds the slide area. Split bullets, table rows or chart across slides.')
  return { top, subtitleHeight, bulletsHeight, tableTop, rowHeights, chartTop }
}

export function auditDeck(slides: DeckSlide[]): DeckFinding[] {
  const findings: DeckFinding[] = []
  const titles = new Map<string, number>()
  slides.forEach((slide, index) => {
    const number = index + 1
    try { deckBodyLayout(slide) } catch (error) { findings.push(line(number, 'overflow', (error as Error).message)) }
    const bullets = slide.bullets ?? []
    const texts = [slide.title, slide.subtitle ?? '', ...bullets]
    if (!slide.title.trim() && bullets.every((one) => !one.trim()) && !slide.table && !slide.chart) findings.push(line(number, 'empty', '(no text)'))
    for (const text of texts) {
      if (!text) continue
      if (PLACEHOLDER.test(text)) findings.push(line(number, 'placeholder', text))
      if (PROCESS.test(text)) findings.push(line(number, 'process', text))
    }
    if (slide.title.length > TITLE_CAP) findings.push(line(number, 'overflow', `title is ${slide.title.length} characters; keep it under ${TITLE_CAP}`))
    for (const bullet of bullets) if (bullet.length > BULLET_CAP) findings.push(line(number, 'overflow', `a bullet is ${bullet.length} characters; keep each under ${BULLET_CAP}`))
    if (bullets.length > BULLETS_CAP) findings.push(line(number, 'overflow', `${bullets.length} bullets; keep at most ${BULLETS_CAP} per slide`))
    const key = slide.title.trim().toLocaleLowerCase()
    if (key) {
      const seen = titles.get(key)
      if (seen !== undefined) findings.push(line(number, 'duplicate', `same title as slide ${seen}: ${slide.title}`))
      else titles.set(key, number)
    }
  })
  return findings
}

// One paragraph the model can act on, or an empty string when the deck reads
// clean.
export function describeDeckFindings(findings: DeckFinding[]): string {
  if (findings.length === 0) return ''
  const lines = findings.slice(0, 12).map((one) => `slide ${one.slide} · ${one.kind}: ${one.text}`)
  const more = findings.length > 12 ? ` (+${findings.length - 12} more)` : ''
  return `The deck does not read clean yet${more}:\n${lines.join('\n')}\nFix these and build it again.`
}
