import { afterEach, expect, it, vi } from 'vitest'
vi.mock('electron', () => ({ net: { fetch: (...args: Parameters<typeof fetch>) => fetch(...args) } }))
import { siteIcon } from '../src/main/site-icons.js'
afterEach(() => vi.unstubAllGlobals())
it('bounds icon downloads, omits credentials and preserves browser-supported bitmap formats', async () => {
  const request = vi.fn(async () => new Response(new Uint8Array([1, 2]), { headers: { 'content-type': 'image/png' } }))
  vi.stubGlobal('fetch', request)
  expect(await siteIcon('https://icons.example')).toBe('data:image/png;base64,AQI=')
  await siteIcon('https://icons.example')
  expect(request).toHaveBeenCalledOnce()
  request.mockImplementation(async () => new Response(new Uint8Array([0, 0, 1, 0]), { headers: { 'content-type': 'image/x-icon' } }))
  expect(await siteIcon('https://bitmap.example')).toBe('data:image/x-icon;base64,AAABAA==')
  expect(request).toHaveBeenCalledWith('https://icons.example/favicon.ico', expect.objectContaining({ credentials: 'omit', redirect: 'error' }))
  for (const url of ['file:///secret', 'http://intranet', 'https://user:password@example.com', 'https://example.com/private', 'https://example.com:8443']) expect(await siteIcon(url)).toBeNull()
  expect(request).toHaveBeenCalledTimes(2)
  request.mockImplementation(async () => new Response(new Uint8Array(129 * 1024), { headers: { 'content-type': 'image/png' } }))
  expect(await siteIcon('https://large.example')).toBeNull()
  request.mockImplementation(async () => new Response('<svg/>', { headers: { 'content-type': 'image/svg+xml' } }))
  expect(await siteIcon('https://vector.example')).toBeNull()
})
