import { beforeEach, expect, it, vi } from 'vitest'
let webPane: typeof import('../src/renderer/src/lib/webPane.js').webPane
beforeEach(async () => { vi.resetModules(); webPane = (await import('../src/renderer/src/lib/webPane.js')).webPane })
const step = (channel: string, tool: string) => webPane.handleEvent({ type: 'comet:step', channel, line: `${tool}: page` })
it('opens actual browser tools in their own chat, preserving each fold and phase through parallel work', () => {
  expect(step('a', 'open_page')).toBe(true)
  expect(webPane.getSnapshot('a')).toEqual({ folded: false, wanted: true, phase: 'working' })
  expect(webPane.getSnapshot('b')).toEqual({ folded: false, wanted: false, phase: 'idle' })
  webPane.fold('a')
  expect(step('b', 'read_open_page')).toBe(true)
  expect(step('a', 'scroll')).toBe(false)
  expect(webPane.getSnapshot('a').folded).toBe(true)
  expect(webPane.getSnapshot('b').folded).toBe(false)
  step('a', 'aside')
  expect(webPane.getSnapshot('a').phase).toBe('aside')
  expect(webPane.getSnapshot('b').phase).toBe('working')
  step('a', 'resume')
  step('a', 'excel_write')
  expect(webPane.getSnapshot('a').phase).toBe('idle')
  expect(step('a', 'open_page')).toBe(true)
  expect(webPane.getSnapshot('a').folded).toBe(false)
  webPane.handleEvent({ type: 'chat:error', channel: 'b', message: 'Stopped' })
  expect(webPane.getSnapshot('b')).toEqual({ folded: false, wanted: true, phase: 'idle' })
  expect(webPane.getSnapshot('a').phase).toBe('working')
})
it('does not mistake memory reads or app launching for browser work', () => {
  for (const tool of ['open_skill', 'read_note', 'open_app', 'read_live_document']) expect(step('a', tool)).toBe(false)
  expect(webPane.getSnapshot('a').wanted).toBe(false)
})
